#!/usr/bin/env python3
"""Turn vendored SVG marks into a Rust table of terminal cells.

Run at development time, never at runtime, so the binary stays one file with no
image stack in it:

    python3 scripts/logos.py            # -> src/logos.rs
    python3 scripts/logos.py --preview  # -> ANSI on stdout, to look at

Three things happen here that are worth knowing about.

**The cell is chosen, not assumed.** A logo is rasterised far larger than it
will be shown, area-averaged down to an exact coverage value per sub-cell, and
then every cell picks the glyph that reproduces its own 8x8 patch best --
space, full block, halves, all ten quadrants, and both eighth-block ramps --
by least squares over a two-level fit. Quadrants and eighths give sub-cell
precision while still *filling*, which is what a mark needs and what a plain
half-block render cannot do: at 16 cells wide a naive downsample leaves grey
fringes on every edge.

**Braille is deliberately not in the candidate set,** even though it has four
times the vertical resolution. Braille dots never touch, so where the search
picks one it leaves a dotted fringe along an edge that ought to be solid. It is
the right medium for texture and the wrong one for a logo -- the same
conclusion the map arrived at from the other direction.

**Alphas are stored, not colours.** Each cell keeps a glyph and two coverage
values rather than two RGB triples, so the application can dim a tool a project
did not use, or light one as it lifts under the cursor, without regenerating
anything.
"""
import glob
import json
import os
import re
import sys

from PIL import Image, ImageDraw, ImageFont, ImageOps
from reportlab.graphics import renderPM
from svglib.svglib import svg2rlg

SHEET = r"""
/// Every mark, laid out as a contact sheet. A development aid: these are
/// generated by a script that cannot see a terminal, so this is how you find
/// out whether one of them came out as mush.
pub fn sheet() -> String {
    const BG: (u8, u8, u8) = (6, 7, 10);
    let blend = |c: (u8, u8, u8), a: u8| {
        let a = a as f32 / 255.0;
        (
            (BG.0 as f32 + (c.0 as f32 - BG.0 as f32) * a) as u8,
            (BG.1 as f32 + (c.1 as f32 - BG.1 as f32) * a) as u8,
            (BG.2 as f32 + (c.2 as f32 - BG.2 as f32) * a) as u8,
        )
    };
    let mut out = String::new();
    for row in LOGOS.chunks(6) {
        for r in 0..row[0].lg.rows as usize {
            for l in row {
                let a = &l.lg;
                for c in 0..a.cols as usize {
                    let (ch, f, b) = a.cells[r * a.cols as usize + c];
                    if f == 0 && b == 0 {
                        out.push_str("\x1b[0m ");
                        continue;
                    }
                    let (fr, fg, fb) = blend(l.rgb, f);
                    let (br, bg, bb) = blend(l.rgb, b);
                    out.push_str(&format!(
                        "\x1b[38;2;{fr};{fg};{fb}m\x1b[48;2;{br};{bg};{bb}m{ch}"
                    ));
                }
                out.push_str("\x1b[0m  ");
            }
            out.push('\n');
        }
        for l in row {
            let n: String = l.name.chars().take(16).collect();
            let pad = (16 - n.chars().count()) / 2;
            out.push_str(&format!(
                "\x1b[38;2;150;155;165m{}{}\x1b[0m{}  ",
                " ".repeat(pad),
                n,
                " ".repeat(16 - pad - n.chars().count())
            ));
        }
        out.push_str("\n\n");
    }
    out
}
"""

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ASSETS = os.path.join(ROOT, "assets", "logos")
OUT = os.path.join(ROOT, "src", "logos.rs")

# Sub-samples per cell on each axis, for the glyph fit.
N = 8
# How much bigger than the final cell grid the vector is rasterised.
SUPER = 6
# Terminal background these are pre-fitted against.
BG = (6, 7, 10)
# Sizes generated for every mark: (cols, rows).
SIZES = {"lg": (16, 8), "sm": (10, 5)}

# Tools with no mark of their own. A monogram labels rather than inventing a
# brand: three letters set solid in a colour, which is honest about being a
# stand-in. AWS is here because simple-icons dropped it at Amazon's request.
MONOGRAM = {
    "aws": ("AWS", "AWS", "#FF9900"),
    "ssh": ("SSH", "OpenSSH", "#3B8A6E"),
    "systemd": ("SYS", "systemd", "#30D475"),
    "nftables": ("NFT", "nftables", "#9A78C4"),
    "curses": ("CUR", "curses", "#C8A05A"),
    "websockets": ("WS", "WebSockets", "#4FA3D1"),
    "vectortiles": ("MVT", "vector tiles", "#5FA8A0"),
    "planetiler": ("PLT", "Planetiler", "#7FB069"),
}

# Marks whose own colour is unusable on a dark terminal keep their hue and
# gain luminance. Black is a legitimate brand colour and an illegible one here.
MIN_LUMA = 96.0

# A few marks are specified in a colour that only makes sense on white. Lifting
# the luminance of near-black leaves a muddy grey; these say what they should be
# on a dark ground instead.
OVERRIDE = {
    "tailscale": (242, 242, 244),
    "rust": (226, 128, 92),
    "webrtc": (172, 178, 190),
    "openjdk": (226, 230, 236),
}


def luma(c):
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]


def lift(hexstr):
    c = tuple(int(hexstr[i : i + 2], 16) for i in (1, 3, 5))
    if max(c) < 24:  # essentially black: no hue to preserve, go to paper white
        return (228, 230, 234)
    y = luma(c)
    if y >= MIN_LUMA:
        return c
    k = MIN_LUMA / max(y, 1.0)
    return tuple(min(255, int(v * k)) for v in c)


# ── candidate glyphs ─────────────────────────────────────────────────────────


def box(x0, y0, x1, y1):
    return [
        [1.0 if (x0 <= x < x1 and y0 <= y < y1) else 0.0 for x in range(N)]
        for y in range(N)
    ]


def merge(*ms):
    return [[min(1.0, sum(m[y][x] for m in ms)) for x in range(N)] for y in range(N)]


def candidates():
    out = [(" ", box(0, 0, 0, 0)), ("█", box(0, 0, N, N))]
    out += [
        ("▀", box(0, 0, N, 4)),
        ("▄", box(0, 4, N, N)),
        ("▌", box(0, 0, 4, N)),
        ("▐", box(4, 0, N, N)),
    ]
    quad = {
        "▘": [(0, 0)], "▝": [(1, 0)], "▖": [(0, 1)], "▗": [(1, 1)],
        "▚": [(0, 0), (1, 1)], "▞": [(1, 0), (0, 1)],
        "▛": [(0, 0), (1, 0), (0, 1)], "▜": [(0, 0), (1, 0), (1, 1)],
        "▙": [(0, 0), (0, 1), (1, 1)], "▟": [(1, 0), (0, 1), (1, 1)],
    }
    for ch, qs in quad.items():
        out.append((ch, merge(*[box(x * 4, y * 4, x * 4 + 4, y * 4 + 4) for x, y in qs])))
    for k, ch in enumerate("▁▂▃▅▆▇", start=1):
        h = k if k < 4 else k + 1
        out.append((ch, box(0, N - h, N, N)))
    for k, ch in enumerate("▏▎▍▋▊▉", start=1):
        w = k if k < 4 else k + 1
        out.append((ch, box(0, 0, w, N)))
    # Precompute the parts of the normal equations that do not involve the
    # source, so the per-cell fit is a handful of multiplies.
    prepped = []
    for ch, m in out:
        flat = [m[y][x] for y in range(N) for x in range(N)]
        saa = sum(a * a for a in flat)
        sbb = sum((1 - a) * (1 - a) for a in flat)
        sab = sum(a * (1 - a) for a in flat)
        det = saa * sbb - sab * sab
        prepped.append((ch, flat, saa, sbb, sab, det))
    return prepped


CAND = candidates()


def fit(src):
    """Best (glyph, fg, bg) for one cell's 8x8 coverage patch."""
    best = None
    for ch, m, saa, sbb, sab, det in CAND:
        sya = syb = 0.0
        for i, a in enumerate(m):
            s = src[i]
            sya += s * a
            syb += s * (1.0 - a)
        if abs(det) < 1e-9:
            v = min(1.0, max(0.0, (sya + syb) / max(1e-9, saa + sbb)))
            fg = bg = v
        else:
            fg = min(1.0, max(0.0, (sya * sbb - syb * sab) / det))
            bg = min(1.0, max(0.0, (syb * saa - sya * sab) / det))
        err = 0.0
        for i, a in enumerate(m):
            err += (src[i] - (fg * a + bg * (1.0 - a))) ** 2
        if best is None or err < best[0]:
            best = (err, ch, fg, bg)
    return best[1], best[2], best[3]


# ── rasterising ──────────────────────────────────────────────────────────────


def from_svg(path, w, h):
    d = svg2rlg(path)
    k = max(w, h) * N * SUPER / max(d.width, d.height)
    d.scale(k, k)
    d.width, d.height = d.width * k, d.height * k
    tmp = path + ".ppm"
    renderPM.drawToFile(d, tmp, fmt="PNG", bg=0xFFFFFF)
    im = ImageOps.invert(Image.open(tmp).convert("L"))
    os.remove(tmp)
    return im


def from_text(text, w, h):
    big = Image.new("L", (w * N * SUPER, h * N * SUPER), 0)
    dr = ImageDraw.Draw(big)
    for size in range(big.height, 8, -4):
        try:
            f = ImageFont.truetype(
                "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", size
            )
        except OSError:
            f = ImageFont.load_default()
        l, t, r, b = dr.textbbox((0, 0), text, font=f)
        if r - l <= big.width * 0.94 and b - t <= big.height * 0.94:
            dr.text(((big.width - (r - l)) / 2 - l, (big.height - (b - t)) / 2 - t),
                    text, fill=255, font=f)
            break
    return big


def cells_for(im, cols, rows):
    """Trim to the ink, refit, area-average, then fit a glyph per cell."""
    bb = im.point(lambda p: 255 if p > 8 else 0).getbbox()
    if bb:
        im = im.crop(bb)
    tw, th = cols * N, rows * N
    # One cell of air so nothing touches the tile edge.
    inner_w, inner_h = tw - N, th - N

    # A terminal cell is about twice as tall as it is wide, so a subsample row
    # covers twice the screen height that a subsample column covers width. The
    # array is therefore NOT square on screen, and fitting to it as if it were
    # is what stretches every mark into an oval. The scale is chosen in screen
    # units and only then converted back to array counts.
    k = min(inner_w / im.width, 2.0 * inner_h / im.height)
    nw = max(1, round(im.width * k))
    nh = max(1, round(im.height * k / 2.0))
    im = im.resize((nw, nh), Image.LANCZOS)
    canvas = Image.new("L", (tw, th), 0)
    canvas.paste(im, ((tw - nw) // 2, (th - nh) // 2))
    px = canvas.load()
    out = []
    for cy in range(rows):
        for cx in range(cols):
            patch = [
                px[cx * N + x, cy * N + y] / 255.0 for y in range(N) for x in range(N)
            ]
            out.append(fit(patch) if max(patch) > 0.02 else (" ", 0.0, 0.0))
    return out


# ── emit ─────────────────────────────────────────────────────────────────────


def rust_char(ch):
    return "' '" if ch == " " else f"'\\u{{{ord(ch):x}}}'"


def main():
    brand = json.load(open(os.path.join(ASSETS, "brand.json")))
    marks = []

    for path in sorted(glob.glob(os.path.join(ASSETS, "*.svg"))):
        slug = os.path.basename(path)[:-4]
        meta = brand.get(slug, {})
        rgb = OVERRIDE.get(slug) or lift(meta.get("hex", "#C8C8C8"))
        marks.append((slug, meta.get("title", slug), rgb,
                      lambda p=path, w=0, h=0: from_svg(p, w, h)))
    for slug, (text, title, hexstr) in MONOGRAM.items():
        marks.append((slug, title, lift(hexstr),
                      lambda t=text, w=0, h=0: from_text(t, w, h)))

    preview = "--preview" in sys.argv
    body, index = [], []
    for slug, title, rgb, make in sorted(marks):
        entries = []
        for key, (cols, rows) in SIZES.items():
            im = make(w=cols, h=rows)
            cs = cells_for(im, cols, rows)
            name = f"{re.sub(r'[^a-z0-9]', '_', slug.lower()).upper()}_{key.upper()}"
            body.append(
                f"const {name}: [Cell; {cols * rows}] = [\n    "
                + ",\n    ".join(
                    f"({rust_char(c)}, {round(f * 255)}, {round(b * 255)})" for c, f, b in cs
                )
                + ",\n];"
            )
            entries.append((key, cols, rows, name))
        lg = next(e for e in entries if e[0] == "lg")
        sm = next(e for e in entries if e[0] == "sm")
        index.append(
            f'    Logo {{ id: "{slug}", name: "{title}", rgb: ({rgb[0]}, {rgb[1]}, {rgb[2]}),\n'
            f"           lg: Art {{ cols: {lg[1]}, rows: {lg[2]}, cells: &{lg[3]} }},\n"
            f"           sm: Art {{ cols: {sm[1]}, rows: {sm[2]}, cells: &{sm[3]} }} }},"
        )
        print(f"  {slug:<22} {title}", file=sys.stderr)

    src = (
        "#![allow(dead_code)]\n"
        "//! Tool marks, as terminal cells. GENERATED by scripts/logos.py -- do\n"
        "//! not edit. Each cell is a glyph plus the coverage of the mark's own\n"
        "//! colour in front and behind it, so a mark can be dimmed or lit\n"
        "//! without being regenerated.\n\n"
        "/// glyph, foreground coverage, background coverage\n"
        "pub type Cell = (char, u8, u8);\n\n"
        "pub struct Art {\n    pub cols: u16,\n    pub rows: u16,\n"
        "    pub cells: &'static [Cell],\n}\n\n"
        "pub struct Logo {\n    pub id: &'static str,\n    pub name: &'static str,\n"
        "    pub rgb: (u8, u8, u8),\n    pub lg: Art,\n    pub sm: Art,\n}\n\n"
        "impl Logo {\n"
        "    pub fn art(&self, small: bool) -> &Art {\n"
        "        if small { &self.sm } else { &self.lg }\n    }\n}\n\n"
        "pub fn find(id: &str) -> Option<&'static Logo> {\n"
        "    LOGOS.iter().find(|l| l.id == id)\n}\n\n"
        + "\n\n".join(body)
        + "\n\npub const LOGOS: &[Logo] = &[\n"
        + "\n".join(index)
        + "\n];\n"
        + SHEET
    )
    open(OUT, "w").write(src)
    print(f"\n{len(marks)} marks -> {os.path.relpath(OUT, ROOT)} "
          f"({len(src) // 1024} KB)", file=sys.stderr)


if __name__ == "__main__":
    main()
