#!/usr/bin/env python3
"""Bake the tip codes into portfolio/src/coffee.rs.

    python3 portfolio/scripts/coffee.py > portfolio/src/coffee.rs

Baked rather than encoded at runtime for the same reason the portraits are:
the payloads never change, and a QR encoder is a few hundred lines of
Reed-Solomon and mask selection to compute a constant. There is no QR crate in
the offline registry to do it with either.

OpenCV does both halves here, which is the point: every code is encoded and then
*decoded again* before it is written out, and the script refuses to emit one
that does not read back byte for byte. A tip QR that does not scan is worse than
no tip QR -- it fails silently, in someone else's hands, and nobody tells you.
"""

import sys

import cv2
import numpy as np

CODES = [
    (
        "UPI",
        "upi",
        "upi://pay?pa=prince2412001@okicici&pn=Prince%20Patel&aid=uGICAgIDNz5SkIQ",
        "any UPI app in India",
    ),
    (
        "CARD",
        "card",
        "https://buymeacoffee.com/snufkin24",
        "buymeacoffee.com/snufkin24",
    ),
]


def encode(payload):
    """A QR matrix as rows of booleans, dark = True. Verified by decoding it."""
    img = cv2.QRCodeEncoder_create().encode(payload)

    # Scaled and quiet-zoned before decoding: the detector wants something that
    # looks like a photograph of a code, not a 37-pixel thumbnail. This is only
    # for the check -- what gets baked is the raw matrix.
    big = cv2.resize(img, None, fx=8, fy=8, interpolation=cv2.INTER_NEAREST)
    big = cv2.copyMakeBorder(big, 48, 48, 48, 48, cv2.BORDER_CONSTANT, value=255)
    read, _, _ = cv2.QRCodeDetector().detectAndDecode(big)
    if read != payload:
        raise SystemExit(
            f"refusing to bake a code that does not scan.\n"
            f"  wanted: {payload!r}\n"
            f"  read:   {read!r}"
        )

    # OpenCV gives 0 for dark and 255 for light, and wraps the code in a
    # two-module quiet zone of its own. Two is under the spec's four, and the
    # renderer adds its own anyway -- so the border is trimmed back to the bare
    # matrix here and the question of how much white space belongs around it is
    # left to whoever is drawing it.
    m = np.asarray(img) == 0
    while m.shape[0] > 8 and not (m[0].any() or m[-1].any() or m[:, 0].any() or m[:, -1].any()):
        m = m[1:-1, 1:-1]
    return m.tolist()


def main():
    out = sys.stdout.write
    out(
        "//! GENERATED by portfolio/scripts/coffee.py -- do not edit.\n"
        "//!\n"
        "//! Tip codes, as matrices. Every one of these was decoded back to its\n"
        "//! payload by the script that wrote it; see the module doc there for why\n"
        "//! that check is not optional.\n\n"
        "/// One QR code. `rows` are top to bottom, `#` dark and `.` light, with\n"
        "/// no quiet zone -- the renderer adds that, because how much white space\n"
        "/// a code needs is a question about the screen and not about the code.\n"
        "#[derive(Debug)]\n"
        "pub struct Code {\n"
        "    pub size: usize,\n"
        "    pub rows: &'static [&'static str],\n"
        "    /// What it pays, in a few words, for the line under it.\n"
        "    pub how: &'static str,\n"
        "    /// The payload, for anyone who would rather type than scan.\n"
        "    pub payload: &'static str,\n"
        "}\n\n"
    )

    names = []
    for const, key, payload, how in CODES:
        matrix = encode(payload)
        size = len(matrix)
        names.append((const, key))
        out(f"pub const {const}: Code = Code {{\n")
        out(f"    size: {size},\n")
        out("    rows: &[\n")
        for row in matrix:
            line = "".join("#" if dark else "." for dark in row)
            out(f'        "{line}",\n')
        out("    ],\n")
        out(f'    how: "{how}",\n')
        out(f'    payload: "{payload}",\n')
        out("};\n\n")

    out("/// Every code, for the tests and for whatever asks.\n")
    out(f"pub const ALL: [(&str, &Code); {len(names)}] = [\n")
    for const, key in names:
        out(f'    ("{key}", &{const}),\n')
    out("];\n")


if __name__ == "__main__":
    main()
