//! GENERATED by portfolio/scripts/cert.py -- do not edit.
//!
//! The certification badge, drawn rather than photographed. See the
//! script for why: at the size this has to fit, a chafa bake of the
//! real PNG loses every word on it, and the words are the credential.
//!
//! `pixels` is the plate, half-blocked -- one cell is two rows of this
//! grid -- and `words` is everything with detail in it: the three lines
//! and the mark, set by the terminal in its own font over the top.
//! A character the font already knows is not one worth dithering.

/// The badge as a grid: `.` is the page and `p` the plate.
/// Two rows to a cell, top to bottom.
pub struct Badge {
    /// Cells across, and the length of every row in `pixels`.
    pub w: usize,
    /// Cells down. `pixels` has twice this many rows.
    pub h: usize,
    pub pixels: &'static [&'static str],
    /// Type over the plate: cell row, cell column, and the line. In
    /// the terminal's own font, on the plate's colour.
    pub words: &'static [(usize, usize, &'static str)],
}

pub const PLATE: (u8, u8, u8) = (217, 119, 87);
pub const INK: (u8, u8, u8) = (250, 249, 245);

pub const BADGE: Badge = Badge {
    w: 40,
    h: 20,
    pixels: &[
        "........................................",
        ".............pppppppppppppp.............",
        "............pppppppppppppppp............",
        "..........pppppppppppppppppppp..........",
        ".........pppppppppppppppppppppp.........",
        "........pppppppppppppppppppppppp........",
        "......pppppppppppppppppppppppppppp......",
        ".....pppppppppppppppppppppppppppppp.....",
        "....pppppppppppppppppppppppppppppppp....",
        "...pppppppppppppppppppppppppppppppppp...",
        "...pppppppppppppppppppppppppppppppppp...",
        "...pppppppppppppppppppppppppppppppppp...",
        "..pppppppppppppppppppppppppppppppppppp..",
        "..pppppppppppppppppppppppppppppppppppp..",
        "..pppppppppppppppppppppppppppppppppppp..",
        ".pppppppppppppppppppppppppppppppppppppp.",
        ".pppppppppppppppppppppppppppppppppppppp.",
        ".pppppppppppppppppppppppppppppppppppppp.",
        "pppppppppppppppppppppppppppppppppppppppp",
        "pppppppppppppppppppppppppppppppppppppppp",
        "pppppppppppppppppppppppppppppppppppppppp",
        "pppppppppppppppppppppppppppppppppppppppp",
        ".pppppppppppppppppppppppppppppppppppppp.",
        ".pppppppppppppppppppppppppppppppppppppp.",
        ".pppppppppppppppppppppppppppppppppppppp.",
        "..pppppppppppppppppppppppppppppppppppp..",
        "..pppppppppppppppppppppppppppppppppppp..",
        "..pppppppppppppppppppppppppppppppppppp..",
        "...pppppppppppppppppppppppppppppppppp...",
        "...pppppppppppppppppppppppppppppppppp...",
        "...pppppppppppppppppppppppppppppppppp...",
        "....pppppppppppppppppppppppppppppppp....",
        ".....pppppppppppppppppppppppppppppp.....",
        "......pppppppppppppppppppppppppppp......",
        "........pppppppppppppppppppppppp........",
        ".........pppppppppppppppppppppp.........",
        "..........pppppppppppppppppppp..........",
        "............pppppppppppppppp............",
        ".............pppppppppppppp.............",
        "........................................",
    ],
    words: &[
        (3, 9, "F O U N D A T I O N S"),
        (7, 19, "✳"),
        (12, 12, "Claude Certified"),
        (14, 15, "Architect"),
    ],
};

/// What it is called, for the one line on the landing page.
pub const NAME: &str = "Claude Certified Architect";
pub const TIER: &str = "FOUNDATIONS";
pub const ISSUER: &str = "Anthropic";
/// Short enough to read off a screen and type.
pub const SHOWN: &str = "credly.com/badges/64147a78";

/// The verification link, as a code. Decoded back to the URL by the
/// script that wrote it -- see `coffee.rs` for why that is not
/// optional. Typed as a tip code because it is the same thing: a
/// matrix and the string it stands for.
pub const QR: crate::coffee::Code = crate::coffee::Code {
    size: 33,
    rows: &[
        "#######..###....####.#.#..#######",
        "#.....#.#....#.##...###...#.....#",
        "#.###.#..#.....##....###..#.###.#",
        "#.###.#.#.#..#.#.##.#.#.#.#.###.#",
        "#.###.#....#..#.#..#.###..#.###.#",
        "#.....#.###....##...#...#.#.....#",
        "#######.#.#.#.#.#.#.#.#.#.#######",
        ".........#.#....#.#..##..........",
        "#####.####.#.#.######...##.#.#.#.",
        "....##........#....#...#..#...###",
        "..######..#...#####...#..#...#.#.",
        "##.........##.##....###.#.....#..",
        "#.######.##.##.#.##.....##.###...",
        "##..#...#..#..#.##.#####..#....##",
        "##..####.#...#.#..#...#.#####..#.",
        "#......##...#.....##.#.##..#..#..",
        ".#.#.##.#..###.#.##.#...##..#..#.",
        "###.##..####..#.#..#.###.##..#.##",
        "......###.#.#..####.###...#.##.#.",
        "...#.....#....##..#.##.#.#.#..#..",
        ".##...#.##.###.#.###...##..##..#.",
        "#....#.##..#.##.####.####.#..#.##",
        "#.##..#...#.#..##....#...#####.#.",
        "#...##..#..##..##....##...#.###..",
        "##...##.....##...####..#######..#",
        "........#.##..#..#.#.##.#...###.#",
        "#######.#.#..####.#.#####.#.##.#.",
        "#.....#........#...###.##...####.",
        "#.###.#.###..#.####.#...######.##",
        "#.###.#.##.#.#.....#.###.#.####..",
        "#.###.#.#...####.##.#.##..##.#.#.",
        "#.....#.#...#.#......##.....###..",
        "#######.#.#..######...#####..#.#.",
    ],
    how: "credly, and it is public",
    payload: "https://www.credly.com/badges/64147a78-2d91-4382-9321-aba7eb052186/public_url",
};
